### ISSUE TITLE
What is the license of this repository?

### ISSUE THREAD

**Issue by koreyou** [pl8787/textnet-release#4]
Hello. Thanks for sharing us a great framework.

Do you mind specifying a license of this project?

**Comment by pl8787** [comment]
We follow the Apache License version 2.0.

**Comment by koreyou** [comment]
Thanks for a prompt reply + adding LICENSE file to the repository!
Does the license also apply to the model repository ( https://github.com/pl8787/textnet-model )?

**Comment by pl8787** [comment]
Yes, I add LICENSE too.

**Comment by koreyou** [comment]
Thank you very much.
Closing the issue.
